male(goba).
male(gobra).
male(pepe).
male(chalu).
male(anil).
male(alu).
female(mita).
female(kali).
female(apu).
female(jhinge).
parents(kali,goba,mita).
parents(chalu,goba,mita).
parents(jhinge,gobra,kali).
parents(pepe,gobra,kali).
parents(anil,chalu,apu).
parents(alu,chalu,apu).
father(X,Y):-male(X),parents(Y,X,_).
mother(X,Y):-female(X),parents(Y,_,X).
grandfather(X,Y):-male(X),father(Z,Y),father(X,Z).
grandfather(X,Y):-male(X),mother(Z,Y),father(X,Z).
grandmother(X,Y):-female(X),father(Z,Y),mother(X,Z).
grandmother(X,Y):-female(X),mother(Z,Y),mother(X,Z).